# --------------------User Testing--------------------
GET https://sbd-kelompok-2.vercel.app/user
###

GET https://sbd-kelompok-2.vercel.app/user/639c8a8542314770f1f3e87f
###

POST https://sbd-kelompok-2.vercel.app/user HTTP/1.1
Content-Type: application/json

{
    "name": "daniel",
    "email": "daniel@gmail.com",
    "password": "secretpasswordthatyoucantguess",
    "address": "rumah",
    "company": "PT. IndRadiance"
}

###

DELETE https://sbd-kelompok-2.vercel.app/user/63a6d61aa698fe645f1e2583
###

PATCH https://sbd-kelompok-2.vercel.app/user/63a6d9891b99d03401eb5408 HTTP/1.1
Content-Type: application/json

{
    "name": "daniel updated",
    "email": "danielupdated@gmail.com",
    "password": "secretpasswordthatyoucantguess",
    "address": "rumah",
    "company": "PT. Nuklindo"
}
###

# --------------------Products Testing--------------------
GET https://sbd-kelompok-2.vercel.app/product
###

GET https://sbd-kelompok-2.vercel.app/product/63a2af04c88ec0ff9b0a8349
###

POST https://sbd-kelompok-2.vercel.app/product HTTP/1.1
Content-Type: application/json

{
    "title": "Ir-192",
    "description": "this product usually used for industrial NDT",
    "left": "Rp. 3.500.000,-",
    "right": "Jakarta",
    "image": "https://www.oserix.com/web/image/887/ir_attachment_2963.png"
}
###

DELETE https://sbd-kelompok-2.vercel.app/product/63a6fe6107e0672d57d36c97
###

PATCH https://sbd-kelompok-2.vercel.app/product/63a6fe6107e0672d57d36c97 HTTP/1.1
Content-Type: application/json

{
    "title": "Ir-192 updated",
    "description": "this product usually used for industrial NDT",
    "left": "Rp. 2.500.000,-",
    "right": "Batam",
    "image": "https://www.oserix.com/web/image/887/ir_attachment_2963.png"
}